config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'tasks#all'
  get 'tasks/new', to: 'tasks#new'
  get 'tasks/:id', to: 'tasks#show', as: :task
  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  post 'tasks', to: 'tasks#create'
  delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def all
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task.update(task_params)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/all.html.erb
<h1>My Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to "#{task.name}", task_path(task.id) %></li>
  <% end %>
</ul>
<br>
<br>
<p><%= link_to "Add a new task", tasks_new_path %></p>

app/views/tasks/edit.html.erb
<h1>Update task</h1>
<br>
<%= form_for(@task) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.text_field :completed %>
  <%= link_to f.submit, task_path(@task.id) %>
<% end %>

app/views/tasks/new.html.erb
<h1>Add a new task</h1>
<br>
<%= render "form", task: @task %>
<br>
<br>
<p><%= link_to "Back to tasks list", tasks_path %></p>

app/views/tasks/show.html.erb
<h2><%= @task.name %></h2>
<p><%= @task.details %></p>
<p>Completed: <%= @task.completed %></p>
<br>
<br>
<p><%= link_to "Edit this task", edit_task_path(@task.id) %></p>
<p><%= link_to "Delete this task", destroy_task_path(@task.id), method: :delete %></p>
<p><%= link_to "Back to tasks list", tasks_path %></p>